Task 1: Basic components
egor-mishin/top-courses pull request #1
Opened 2023-07-09 15:45 UTC by egor-mishin

- add Htag component
- add Ptag component
- add Atag component
- add PostImage component
- add PostDate component
- add PostTime component
- add Card component

2023-07-12 09:47 UTC, Grinv requested changes

2023-07-12 09:47 UTC, Grinv commented on __data/posts.ts
> +            width: 300,
Если мы к реалиям переходим, то в большинстве случаев нам размеры картинки не передаются, поэтому хорошо бы уметь обрабатывать случаи, когда нам вообще не известно, какая картинка придёт)

2023-07-12 09:47 UTC, Grinv commented on app/globals.css
> +	font-size: 14px;
Зачем font-size тут? Если хочется резетнуть все стили, лучше добавить его в глобальные стили к body

2023-07-12 09:47 UTC, Grinv commented on app/globals.css
> +	margin-bottom: 6px;
Лучше в глобальных стилях именно обнулять margin. И уже в частных случаях, где там нужно, добавлять тот или иной класс к заголовку, который будет уже добавлять определённые отступы.

2023-07-12 09:47 UTC, Grinv commented on app/page.tsx
> +       {posts.map(p=> <Card title={p.title} image={p.image} content={p.content} date={p.createdAt} tags={p.tags} likes={p.likes}/>)}
Да кажется, что проще просто дальше пропсы прокидывать, как они есть)
```javascript
{posts.map(post => <Card  {...post} />)}
```
только в принимающем компоненте надо будет поменять date на createAt

2023-07-12 09:47 UTC, Grinv commented on components/Atag/Atag.tsx
> +        <Ptag size={'s'}>
Хорошая практика - минимализировать вложенность количество нод в дом дереве
Нет смысла каждую ссылку обёртывать в p
Если хочется применить стили от параграфа, просто импортируй его стили и примени к ссылке

2023-07-12 09:47 UTC, Grinv commented on components/Card/Card.tsx
> +        <div className={css.card}>
Лучше всякие ссылки заворачивать к тэг `article`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article
>Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.

2023-07-12 09:47 UTC, Grinv commented on components/LikeButton/LikeButton.tsx
> +import Icon from "../../public/likeIcon.svg";
Советую для public тоже добавить алиас, чтоб обращаться по пути типа
```javascript
import Icon from "@/public/icons/likeIcon.svg";

2023-07-12 09:47 UTC, Grinv commented on components/PostDate/PostDate.tsx
> +const PostImage: FC<IPostDateProps> = ({date}): JSX.Element => {
TYPO PostDate

2023-07-12 09:47 UTC, Grinv commented on components/Ptag/Ptag.tsx
> +            [css.s]: size === 's'
А где `m` и `l`? :)

2023-07-12 09:47 UTC, Grinv commented on components/Htag/Htag.tsx
> +                return <h1 className={css.h1} {...props}>{children}</h1>;
Лучше спрэд добавлять в начало, потому что так можно перезатереть те пропсы, которые передал до этого.
```javascript
return <h1 {...props} className={css.h1}>{children}</h1>;
```
Допустим в данном примере, если мы в `Htag` передадим className, то он перезатрёт тот className, что мы добавили до этого.

2023-07-12 09:47 UTC, Grinv commented on components/PostImage/PostImage.tsx
> +            <Image src={url} alt={title} width={width} height={height}/>
Я бы ещё к стилям добавил `object-fit: cover`
Потому что если нам картинка придёт немного другого соотношения, картинка у нас будет некрасивая. Хочется сохранить её оригинальное соотношение.
Вообще статические размеры хорошо задавать для одиночных картинок, когда мы точно уверены, что нам ничего не прилетит странного.
А с разными списками продуктов/новостей/статей лучше подстаховаться и учесть, что нам может прилететь картинка любого соотношения сторон и размера. В такой случае я бы задавал размеры картинки при помощи внешнего контейнера, а самой картинке задавал аттрибут fill
https://nextjs.org/docs/pages/api-reference/components/image#fill

2023-07-12 09:47 UTC, Grinv commented on public/postImage.png
Давай сделаем заглушку, если у поста нет картинки. Можно типа такой
![image](https://github.com/egor-mishin/top-courses/assets/4070730/ae4681d5-22d4-4e16-a093-e94f19ed1635)

2023-07-13 15:52 UTC, egor-mishin commented on app/globals.css
> +	font-size: 14px;
Это нужно когда используешь rem единицы для размеров... в данном случае можно убрать если использовать пиксели

2023-07-15 08:25 UTC, Grinv approved these changes

2023-07-15 08:25 UTC, Grinv commented on components/Card/Card.tsx
> +import {BLANK_IMAGE_URL} from "@/constants/constants";
Да впринципе нет смысла в константу выносить картинку, можешь её прям тут импортировать.

2023-07-15 08:25 UTC, Grinv commented on components/Card/Card.tsx
> +                <PostImage url={url ? url : BLANK_IMAGE_URL} title={title}/>
Можно так
```javascript
<PostImage url={url ?? BLANK_IMAGE_URL} title={title}/>
```
Либо вообще когда достаёшь url, можно объявить дефолтное значение
```javascript
const { url = BLANK_IMAGE_URL } = image;

2023-07-15 08:25 UTC, Grinv commented on components/Atag/Atag.tsx
> +        <Ptag size={'s'}>
Так и не поправил)

2023-07-15 08:25 UTC, Grinv commented on components/PostImage/PostImage.tsx
> +            <Image src={url} alt={title} fill className={css.image} />
👍

2023-07-15 08:25 UTC, Grinv commented on components/PostDate/PostDate.tsx
> +        <Ptag size={'s'}>{`${date.days} days ago`}</Ptag>
Да можно просто 
```javascript
<Ptag size={'s'}>{date.days} days ago</Ptag>

2023-07-15 08:25 UTC, merged

2023-07-15 08:31 UTC, Grinv commented
Я замёржил. Ещё пара комментариев
1) Отписался ещё по нескольким вещам. Мелочи, поэтому можешь их потом исправить.
2) Обновляй статус задачи в школе, когда посылаешь исправления, потому что я там смотрю. Случайно увидел, что в гите появилось уведомление.
3) Когда что-то поправил - нажимай "Resolve conversation". Так будет точно понятно, что ты пофиксил и будет проще отделить старые комментарии от новых.