review 2 components
egor-mishin/top-courses pull request #2
Opened 2023-07-17 13:24 UTC by egor-mishin

- Refactor app structure 
- Add LikeButton functionality
- Add Header Layout

2023-07-18 12:32 UTC, Grinv requested changes

2023-07-18 13:14 UTC, egor-mishin commented on components/LikeButton/api/patchLikedStatus.ts
> +        const res = await fetch(`${process.env.NEXT_PUBLIC_URL}/posts/${postId}`, {
![Screenshot 2023-07-18 150817](https://github.com/egor-mishin/top-courses/assets/59925795/1783dfcd-8a29-4c8d-b595-d30149834ab6)
Слушай, у меня работает:) проверь пожалуйста ещё раз:) в чём может быть причина?

2023-07-20 05:40 UTC, Grinv approved these changes

2023-07-20 05:40 UTC, Grinv commented on .gitignore
> +.stylelintcache
И всеравно он попал в коммит :)
Если ты что-то добавляешь в gitignore, то последовательность всегда одна - сначала добавляем файл в gitignore, а потом уже создаём сам файл)

2023-07-20 05:40 UTC, Grinv commented on app/(home)/page.module.css
> +@media (width <= 765px) {
Молодец, что применяешь современный синтаксис👍
Тут у нас его обрабатывает postcss и трансформирует в старое правило.
Но на будущее в других проектах убедись, что у тебя обрабатывается данный синтаксис основываясь на поддержке старых версий браузеров.

2023-07-20 05:40 UTC, Grinv commented on components/Logo/Logo.tsx
> +      <Image src={logoUrl} alt="Awsome blog site logo" />
Можно проще) Но тогда не забудь задать width и height
```javascript
<Image src="/icons/logo.svg" alt="Awsome blog site logo" />

2023-07-20 05:40 UTC, Grinv commented on styles/globals.css
> +  font-family: var(--primary-font);
Почему Open Sans? Ты ж уже применил к body шрифт Inter. И тут же применяешь Open Sans.
+ мы нигде не импортируем Open Sans и не факт, что у юзера он есть. Давай всё-таки будем использовать один шрифт

2023-07-20 05:40 UTC, Grinv commented on app/(home)/layout.tsx
> +const inter = Inter({ subsets: ['latin', 'cyrillic'] });
Давай ещё вынесем его в css переменную `primary-font`
Как это сделать - есть в статье у некста (https://nextjs.org/docs/app/api-reference/components/font#variable)

2023-07-20 05:40 UTC, merged