Task 4: Post
egor-mishin/top-courses pull request #4
Opened 2023-07-26 18:16 UTC by egor-mishin

- Add Post page components
- Add Comments compomemts
- Add Comments Form
- Implement React Hook Form

2023-07-28 06:35 UTC, Grinv requested changes

2023-07-28 06:35 UTC, Grinv commented on components/Textarea/Textarea.tsx
> +      {error && <span className={css.errorMessage}>{error.message}</span>}
Всегда будь внимательным с оператором `&&`. Если используешь, всегда думай, что туда может прийти.
Я в прошлый раз скидывал статью, как помнишь.
Но на всякий случай всеравно обезопасил бы.
```javascript
{Boolean(error) && <span className={css.errorMessage}>{error.message}</span>}
```
а может быть даже так:
```javascript
{typeof error === 'object' && <span className={css.errorMessage}>{error.message}</span>}
```
А может даже так:
```javascript
{error instanceof Error && <span className={css.errorMessage}>{error.message}</span>}

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/Comments.tsx
> +    </>
1) Фрагмент не нужен
```javascript
<div className={css.comments}>
   <Htag tag={'h2'}>Comments</Htag>
   {comments?.map((c) => <Comment {...c} key={c.id} />)}
</div>
```
2) Тут больше подходит section
```javascript
<section className={css.comments}>
   <Htag tag={'h2'}>Comments</Htag>
   {comments?.map((c) => <Comment {...c} key={c.id} />)}
</section>

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/components/Comment/Comment.tsx
> +      <Ptag size={'s'}>{body}</Ptag>
Тэги являются часть карточки коммента? Тогда article - это внешняя обёртка
```javascript
<article className={css.comment}>
   <div className={css.userInfo}>
      <span className={css.userName}>{name}</span>
      <dd className={css.userEmail}>{email}</dd>
   </div>
   <Ptag size={'s'}>{body}</Ptag>
</article>

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/components/Comment/Comment.module.css
> +  grid-template-columns: repeat(3, max-content);
У тебя ж внутри 2 элемента. Почему тут указано 3?)

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/components/Comment/Comment.module.css
> +  display: grid;
Grid тут излишен. Хватит и flex

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/components/Comment/Comment.module.css
> +  margin: 20px 0;
А лишний спейс с первом и последнем элементе? 
Я бы вообще вынес все отступы в обёртку, это гораздо удобнее
```css
.comments {
   display: flex;
   gap: 20px;
}
```
и тогда тебе вообще `.comment` не понадобится. И компонент превратится типа в
```javascript
<article className={css.comment}>
   <span className={css.userName}>{name}</span>
   <span className={css.userEmail}>{email}</span>
   <Ptag size={'s'}>{body}</Ptag>
</article>

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/components/Comment/Comment.tsx
> +        <dd className={css.userEmail}>{email}</dd>
Почему `dd`? Он тут точно не подходит)

2023-07-28 06:35 UTC, Grinv commented on modules/Comments/components/CommentForm/CommentForm.tsx
> +      <Button kind={'submit'} type={'submit'} disabled={isSubmitting || !isSubmitSuccessful}>
Вообще не очень согласен про `kind=submit`
Submit - это всё-таки про тип кнопки, а не её стиль.
А если будет кнопка submit, но серо-буро-малинового цвета?
Вообще в дизайн-системах принято виды кнопок называть либо приоритетом
`primary`, 'secondary' и т.д.
Либо цветами 
`red`, `yellow` и т.д.

Ради примера можешь полазить в разных ui kit и посмотреть, как они называют кнопки разных стилей

2023-08-03 06:25 UTC, Grinv requested changes

2023-08-03 06:25 UTC, Grinv commented on app/posts/[postId]/page.tsx
> +  const apiPost = await fetchData<IPost>(`posts/${params.postId}`);
почему apiPost? Давай переименуем в postData

2023-08-03 06:25 UTC, Grinv commented on app/posts/[postId]/page.tsx
> +  const comments = await fetchData<IComment[]>(`posts/${params.postId}/comments`);
А почему нам надо фетчить данные по посту на клиенте? Они юзерозависимые? Вроде нет
Предлагаю это делать на стороне сервера через getServerSideProps

2023-08-03 06:25 UTC, Grinv commented on app/posts/[postId]/page.tsx
> +    notFound();
Если перенесёшь фетч данных в getServerSideProps, можно будет воспользоваться удобным методом редиректа на 404 из самого некста)

https://nextjs.org/docs/pages/api-reference/functions/get-server-side-props#notfound

2023-08-03 06:25 UTC, Grinv commented on app/not-found.tsx
> +            <h2>Not Found</h2>
h1

2023-08-03 06:27 UTC, merged

2023-08-05 16:36 UTC, egor-mishin commented on app/posts/[postId]/page.tsx
> +  const comments = await fetchData<IComment[]>(`posts/${params.postId}/comments`);
Я правильно понимаю, что getServerSideProps не поддерживается в next13?