Task 5 final
egor-mishin/top-courses pull request #5
Opened 2023-07-29 15:04 UTC by egor-mishin

-add project accessibility 
- add project animation
- fix some bugs

2023-08-05 12:26 UTC, Grinv requested changes

2023-08-05 12:26 UTC, Grinv commented on components/Logo/Logo.tsx
> +      <Image src={'/icons/logo.svg'} alt="Site logo" fill />
Тут fill не нужен. Эта иконка не динамическая и ты точно всегда знаешь её размеры. Поэтому лучше задай их через width и height. Если нужно менять потом размеры, ты сможешь это спокойно сделать через класс

2023-08-05 12:26 UTC, Grinv commented on components/LikeButton/LikeButton.tsx
> +    <button className={classes} onClick={onLiked} aria-label={`${count} likes`}>
За то, что прописываешь aria-label и думаешь об accessibility - респект! :)

2023-08-05 12:26 UTC, Grinv commented on modules/Comments/components/CommentForm/CommentForm.tsx
> +      <Button kind={'primary'} type={'submit'} disabled={isSubmitting || !isSubmitSuccessful} onClick={() => clearErrors()}>
Зачем ты везде прописываешь пропс-стрингу, как переменную, можно ж без скобок)
```javascript
<Button kind="primary" type="submit" disabled={isSubmitting || !isSubmitSuccessful} onClick={() => clearErrors()}>

2023-08-05 12:26 UTC, Grinv commented on modules/Posts/Posts.tsx
>    const apiPosts = await fetchData<IPost[]>('posts?userId=1');
Давай воспользуемся всё-таки преимуществами next.js и попробует брать данные на серверной стороне)
Об этом писал тут
https://github.com/egor-mishin/top-courses/pull/4#pullrequestreview-1560306786

2023-08-05 12:26 UTC, Grinv commented on modules/Comments/components/CommentForm/CommentForm.tsx
> +              {...register('comment', { required: { value: true, message: 'Please fill the comment' } })}
Лучше прописать первым пропсом, а то не заметишь, как будешь перезаписывать какие-то данные. Такое не очень просто отловить.

2023-08-05 12:26 UTC, Grinv commented on modules/Posts/Posts.tsx
>    const apiPosts = await fetchData<IPost[]>('posts?userId=1');
И впринципе тебе надо переписать реализацию
Я к себе клонирую, прописываю `npm run dev` и проект валится при фетче данных
Разве я должен разбираться, почему проект не работает из коробки?)

2023-08-05 16:31 UTC, egor-mishin commented on modules/Posts/Posts.tsx
>    const apiPosts = await fetchData<IPost[]>('posts?userId=1');
Я правильно понял, что getServerSideProps уже не поддерживается в next13?

2023-08-05 18:47 UTC, egor-mishin commented on modules/Posts/Posts.tsx
>    const apiPosts = await fetchData<IPost[]>('posts?userId=1');
Исправил, .env.local был .gitignore..., не знаю как так вышло:)

2023-08-05 18:48 UTC, egor-mishin commented on modules/Posts/Posts.tsx
>    const apiPosts = await fetchData<IPost[]>('posts?userId=1');
склонировал, всё работает))

2023-08-05 18:50 UTC, egor-mishin commented on modules/Comments/components/CommentForm/CommentForm.tsx
> +      <Button kind={'primary'} type={'submit'} disabled={isSubmitting || !isSubmitSuccessful} onClick={() => clearErrors()}>
я делаю это автоматически, так привык наверное:) буду контролировать этот момент

2023-08-10 18:11 UTC, Grinv commented on modules/Posts/Posts.tsx
>    const apiPosts = await fetchData<IPost[]>('posts?userId=1');
Отлично!

2023-08-10 18:18 UTC, Grinv approved these changes

2023-08-10 18:18 UTC, Grinv commented on app/posts/[postId]/page.tsx
>    const comments = await fetchData<IComment[]>(`posts/${params.postId}/comments`);
Опять же, как и писал, все это запросы спокойно можно была вынести на сторону сервера и на фронт уже передать чистые пропсы. Заодно бы и потренировался в SSR :)

2023-08-10 18:18 UTC, Grinv commented on app/posts/loading.tsx
> +  return (
```javascript
return <Loader />

2023-08-10 18:18 UTC, Grinv commented on components/Logo/Logo.tsx
> +    <Atag href={'/'} className={css.logo} aria-label="Site logo link">
`aria-label="Site logo link"`
прям знаешь, чем порадовать) Мало, кто об этом задумывается)

2023-08-10 18:18 UTC, Grinv commented on modules/Posts/Posts.tsx
> +  const postData = await fetchData<IPost[]>('posts?userId=1');
Можно было тоже получить на сервере и на клиент уже данные передать

2023-08-10 18:18 UTC, merged

2023-08-10 18:40 UTC, egor-mishin commented on modules/Posts/Posts.tsx
> +  const postData = await fetchData<IPost[]>('posts?userId=1');
То есть все манипуляции с данными будут на сервере